<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 10.03.2019
 * Time: 21:13
 */

class Model_contacts extends Model
{
    public function get_user_db()
    {
        parent::get_user_db(); // TODO: Change the autogenerated stub
        include 'config.php';
        $pdo = new PDO("mysql:host={$db_host}; dbname={$db_name}",
            $db_user, $db_user_pass);

        $data = $pdo
            ->query("SELECT `user`.address, `user`.map_representation, `user`.phone,
         `user`.email,`user`.vk, `user`.twitter, 
         `user`.instagram, `user`.facebook  FROM `user`;")
            ->fetchAll();
        return $data;
    }

}