<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 12.03.2019
 * Time: 20:25
 */

class Model_main extends Model
{
public function get_user_db()
{
    parent::get_user_db(); // TODO: Change the autogenerated stub
    include 'config.php';
    $pdo = new PDO("mysql:host={$db_host}; dbname={$db_name}",
        $db_user, $db_user_pass);

    $data = $pdo
        ->query("SELECT `user`.about, `user`.foto_user, `user`.vk, `user`.twitter, 
         `user`.instagram, `user`.facebook  FROM `user`;")
        ->fetchAll();
    return $data;
}
public function get_data()
{
    parent::get_data(); // TODO: Change the autogenerated stub
    include 'config.php';
    $pdo = new PDO("mysql:host={$db_host}; dbname={$db_name}",
        $db_user, $db_user_pass);

    $data = $pdo
        ->query("SELECT advantages.id, advantages.description, 
         advantages.icon_extension FROM advantages;")
        ->fetchAll();
    return $data;
}
}